print("this code is just written to maintain the strike of 1000 days" )
print("This is maintainance modefication")
print("sick leave")
print("taking leave for now to search sreas")
print("New Year Celebration")
print("just a leave for reading some new topics in c programing laguage")
print("hello")
print("The Gambleling")
print("New Year Celebration")
print("Yaheko, Nagato and Konan")
print("Starting From Today")
print("Tax and day before birthday and ESA Exam Prer")
print("I messed up some things so some days reasons are not there, Now I am going to master advanced features of git and github")
print("Maths Preparation")
