print("this code is just written to maintain the strike of 1000 days" )
print("This is maintainance modefication")
print("sick leave")
print("taking leave for now to search sreas")
print("just a leave for reading some new topics in c programing laguage")